### ISSUE TITLE
Cannot share, terminating exception

### ISSUE THREAD

**Issue by IzikAlgrisi** [LeoNatan/LNExtensionExecutor#2]
IHello i have a same problem.
Can you tell me how use this code for start whatsapp?

**Comment by LeoNatan** [comment]
Using the API is straight forward. You use the same arguments as you would use normally with a `UIActivityViewController`.
In order to execute the WhatsApp sharing extension, you need to find the the extension’s bundle identifier and supply that to the API. 

What exception are you seeing?

**Comment by IzikAlgrisi** [comment]
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to instantiate class named SLRemoteComposeViewController for host connection!'
an that is my code:

```
        let v  = LNExtensionExecutor(extensionBundleIdentifier: "net.whatsapp.WhatsApp.ShareExtension")
        
        v?.execute(withInputItems: [localVideoPath], completionHandler: { (bool, array, error) in
            print("thanks")
        })


```
