### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by mssjappjwt** [LeoNatan/LNExtensionExecutor#3]
Thank you for sharing this amazing class, I want to ask is this class using any private APIs? Because I do want to use this in a production product.

**Comment by LeoNatan** [comment]
Hello,

Yes, this library uses private API but attempts to hide it as much as possible. This was implemented for a previous place of work of mine for enterprise deployment apps, but was later included in AppStore as well (and still is, as far as I know).

**Comment by LeoNatan** [comment]
If you fear having hidden private API, you should only use Apple's `UIActivityViewController`.
