### ISSUE TITLE
Extension bundle identifier

### ISSUE THREAD

**Issue by rserentill** [LeoNatan/LNExtensionExecutor#4]
Hello,

How do I know the extension bundle identifier for the apps I need to share content to? i.e. WhatsApp, FB Messenger, Telegram, etc.

Thanks

**Comment by LeoNatan** [comment]
It used to be simpler in the past, because `UIActivityViewController` was running in-process and you could inspect internal properties. Now, I'd just download the IPA from iTunes and look at the Info.plist of the extension, and get it that way.

**Comment by rserentill** [comment]
Wow, that was really fast!!
Thank you for your answer!

**Comment by LeoNatan** [comment]
Cheers, happy coding!
