### ISSUE TITLE
Sharing a video to WhatsApp

### ISSUE THREAD

**Issue by adirkol** [LeoNatan/LNExtensionExecutor#5]
Hey,
I've been trying to share a video (mp4) to WhatsApp but with no luck.
Everything works great with an image (UIImage), but not a video.

I tried to pass the video in the inputItems as an AVAsset, URL, path, but with no lack.
here's my code:

```
do {
      let executor = try LNExtensionExecutor(extensionBundleIdentifier: "net.whatsapp.WhatsApp.ShareExtension")
      
      executor.execute(withInputItems: [AVAsset(url: VideoURL)], on: self, completionHandler: { completed, returnedItems, activityError in
          guard let activityError = activityError else {
              return
          }
          
          print("Got error: \(activityError.localizedDescription)")
      })
  } catch(let error) {
      print(error.localizedDescription)
  }
```

**Comment by LeoNatan** [comment]
Hello,

If you go through the normal `UIActivityViewController` route, with the same input your provide here, and click the WhatsApp icon, does it work then?

**Comment by adirkol** [comment]
It's impossible to share a photo or a video with the regular `UIActivityViewController ` as documented on WhatsApp. It just doesn't work.

**Comment by LeoNatan** [comment]
What do you mean? If I open the Photos app, select a video and tap share button, WhatsApp is there and works for videos and photos. The Photos app uses a normal `UIActivityViewController` with a private inline layout mode.

**Comment by adirkol** [comment]
> What do you mean? If I open the Photos app, select a video and tap share button, WhatsApp is there and works for videos and photos. The Photos app uses a normal `UIActivityViewController` with a private inline layout mode.

yes, it works

**Comment by adirkol** [comment]
OK. found a solution!
You should pass URL and not AVAsset and it works!
`executor.execute(withInputItems: [URL(string: pathToYourVideo)!],....`

Thanks for your fast reply!

**Comment by LeoNatan** [comment]
Cool! Where does the URL point to? To the `AVAsset`, or do you need to copy it locally first?

**Comment by adirkol** [comment]
It needs to be copied locally first :)

**Comment by LeoNatan** [comment]
😖

Doesn’t sound efficient. Try playing around with some private `PHAsset` URLs, you might have luck with those. As far as I know, these URLs are universal across the device, and should be accessible from the WhatsApp extension process.

**Comment by adirkol** [comment]
Could be.
Specifically, I created this video file via the app, and it's not accessible through `PHAsset` as it's not in the user's Photos yet.

**Comment by LeoNatan** [comment]
Ah yes, if it’s a local file, of course.
