### ISSUE TITLE
SMS and Mail error with identifier not found

### ISSUE THREAD

**Issue by MinhPhuPham** [LeoNatan/LNExtensionExecutor#6]
I used `UIActivity.ActivityType.message` and `UIActivity.ActivityType.mail` system identifier, but can not present share sheet (`UIActivityViewController` still work as normal). 

Msg error: 
```
error: Extension with identifier "com.apple.UIKit.activity.Message" not found 
```

Maybe a new code from Apple has an update about it? 

Xcode 15.3
Swift 5
IOS 16+

**Comment by LeoNatan** [comment]
Hi

I’m not sure about mail and messages, I don’t remember if I’ve ever tried them.

Both of these have a public API you can use to display natively. Does that not work for you?

Thanks

**Comment by MinhPhuPham** [comment]
Thank for your replying,

> Both of these have a public API you can use to display natively

Ah yes, it works for me. But it will increase the code, I'd like to use the function in `LNExtensionExecutor`

**Comment by LeoNatan** [comment]
I will take a look when I have time.

**Comment by MinhPhuPham** [comment]
Thank you so much 😍😍😍

**Comment by LeoNatan** [comment]
I’ve investigated quickly. It seems like mail and messages are implemented locally with `UIActivity` subclasses (for mail, it’s `UIMailActivity`), and they don’t have a traditional out-of-process extension like the rest of the activities. I’ve added support for built-in system activities.
