### ISSUE TITLE
Sharing with X not working

### ISSUE THREAD

**Issue by VladIacobIonut** [LeoNatan/LNExtensionExecutor#7]
Hey,

We're some having trouble when trying to share content via the X (former Twitter) app. The bundle id for the share extension looks fine, as it matches the one in the .plist also when extracting the IPA of the app.

we get `Extension with identifier "com.atebits.Tweetie2.ShareExtension" not found` though. 

Any suggestion for tracking down the issue? 

Thanks

**Comment by LeoNatan** [comment]
Sorry, I missed this issue. Were you able to get it working?

**Comment by ignaspaladinas** [comment]
Hi there.

First of all thank you for sharing this project!

 I've also encountered  this issue when sharing to X (Twitter).
When trying to target the extension via bundle ID I get the same error.
`Extension with identifier "com.atebits.Tweetie2.ShareExtension" not found`

When looking to the completion handler of the native ActivityController noticed that the returned type is `com.apple.UIKit.activity.PostToTwitter`.
So tried using the native `UIActivity.ActivityType.postToTwitter.rawValue`
But it  returns the same error.
`Extension with identifier "com.apple.UIKit.activity.PostToTwitter" not found" UserInfo={NSLocalizedDescription=Extension with identifier "com.apple.UIKit.activity.PostToTwitter" not found}`

**Comment by LeoNatan** [comment]
I think `com.apple.UIKit.activity.PostToTwitter` comes from the old iOS 5-6 days, when there was a built-in share sheet for Twitter in the OS itself. You will have to investigate to see what the actual identifier is. How did you get the `com.atebits.Tweetie2.ShareExtension` identifier? Perhaps it was changed by Twitter to something else?

**Comment by surelyruchi** [comment]
Hi @LeoNatan,

Thanks for the update. I wanted to check if anyone eventually found a workaround or confirmed what the correct share extension identifier for X (Twitter) currently is. I am also facing the same issue - I tried a bunch of possible extensions but nothing works for me. 

Edit: To get the ```com.atebits.Tweetie2.ShareExtension``` identifier I followed the steps to extract X/Twitter IPA and got the share extension Identifier from there. 

```
 ShareExtension.appex % plutil -p Info.plist | grep "CFBundleIdentifier"
  "CFBundleIdentifier" => "com.atebits.Tweetie2.ShareExtension"
```

**Comment by LeoNatan** [comment]
Hi,
The correct id is `com.apple.share.Twitter.post`.

I'm trying to figure out how to create a way in the demo project for people to be able to discover these identifiers easily.

**Comment by surelyruchi** [comment]
Hey, Thanks a lot! this totally works. I've been on this for so long. 

Yes please share how to get the proper identifier, I need to add the similar flow for other platforms and well. It'd be really helpful for me! Any existing article or anything specific to look for would be great help.
 
Again, thanks a lot!

**Comment by LeoNatan** [comment]
1.5.0 out with an updated example project, which allows discovering extension identifiers.

**Comment by surelyruchi** [comment]
Thanks a bunch for this!
